test_greedy: True
test_nepisode: 100 
test_interval: 50000 
log_interval: 50000 
runner_log_interval: 10000 
learner_log_interval: 10000 

epsilon_anneal_time: 500000 # 25-50% of t_max

global_reward: True

buffer_size: 5000 
target_update_interval_or_tau: 200

batch_size: 32
t_max: 2050000

gamma: 0.99 
lr: 0.0005 

name: "advP_ExpoComm_2M"