# --- IQL specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 5000 # 500000 SANDBOX TESTING ------------------------
evaluation_epsilon: 0.0
runner: "episode"

buffer_size: 100 # 5000 SANDBOX TESTING --------------------------------

batch_size: 16 # SANDBOX TESTING, DELETE AFTERWARDS --------------------
t_max: 10000 # SANDBOX TESTING, DELETE AFTERWARDS ----------------------

# update the target network every {} episodes
target_update_interval_or_tau: 200

mac: "ExpoComm_mac"
topk_neighbors: 6 # including itself
attention_dim: 16
agent: "ExpoComm_static" # Default rnn agent
obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train

agent_output_type: "q"
learner: "aux_q_learner"
aux_coef: 0.1 # Coefficient for auxiliary loss
standardise_returns: False
standardise_rewards: True
double_q: True
use_rnn: True
mixer: # Mixer becomes None

pos_flag: False

name: "iql_ExpoComm_static_n6"
