env: struct_marl

env_args:
  map_name: "struct_uc_100"
  struct_type: "struct"
  n_comp: 50
  discount_reward: 0.95
  custom_param:
    k_comp:  48
  state_obs: True
  state_d_rate: True
  state_alphas: False
  obs_d_rate: False
  obs_multiple: False
  obs_all_d_rate: False
  obs_alphas: False
  env_correlation: False
  campaign_cost: True

learner_log_interval: 500 # 25000 SANDBOX
log_interval: 500 # 25000 SANDBOX
runner_log_interval: 500 # 25000 SANDBOX
test_interval: 500 # 25000 SANDBOX
test_nepisode: 10 # 100 SANDBOX
test_greedy: True
t_max: 2050000

common_reward: True