env: "MAgent_Battle"

env_args:
  map_name: battle_view7
  max_cycles: 200 # params in marllib: https://github.com/Replicable-MARL/MARLlib/blob/368c6173577d0f9c0ad70fb5b4b6afa12c864c15/marllib/envs/base_env/config/magent.yaml#L28
  pretrained_ckpt: null
  global_reward: True # False SANDBOX TESTING -------------------------------
  minimap_mode: False # True SANDBOX TESTING --------------------------------
  map_size: 25 # 40 SANDBOX TESTING -----------------------------------------

test_greedy: True
test_nepisode: 100 # 10 in sandbox, original 100 SANDBOX TESTING
test_interval: 50000 # 5000 in sandbox, original 50000 SANDBOX TESTING --------------------------------------
log_interval: 10000 # 5000 in sandbox, original 50000 SANDBOX TESTING ---------------------------------------
runner_log_interval: 10000 # 5000 in sandbox, 10000 SANDBOX TESTING
learner_log_interval: 10000 # 5000 in sandbox, original 10000 SANDBOX TESTING
t_max: 5050000
