env: "MAgent_AdvPursuit"

env_args:
  map_name: adversarial_pursuit_view8
  max_cycles: 200 # params in marllib: https://github.com/Replicable-MARL/MARLlib/blob/368c6173577d0f9c0ad70fb5b4b6afa12c864c15/marllib/envs/base_env/config/magent.yaml#L28
  pretrained_ckpt: "prey_params.pt"
  global_reward: False
  minimap_mode: True
  map_size: 45

test_greedy: True
test_nepisode: 100 # 100 SANDBOX -------------------------
test_interval: 50000 # 50000 SANDBOX -------------------------
log_interval: 50000 # 50000 SANDBOX -------------------------
runner_log_interval: 10000 # 10000 SANDBOX -------------------------
learner_log_interval: 10000 # 10000 SANDBOX -------------------------
t_max: 5050000
